### PR TITLE
add 11.2.2 ( 20D80) hashes

### PR DESCRIPTION
**Pull request by heinthanth**
Screen Shot 2021-03-06 at 11 59 20 AM

### CODE REVIEW

**Comment by 1alessandro1** [comment]
Hashes are from 11.2.2, but are correct.

```
SHA-256 = 66e93f82c90c4333bc2ca7c0ffbbe536834a162d2670b9d3cd6cf45614ba1c0c
SHA-1: = 6b20ebd588d2e9207cf947f5918194953be30e6c
```

**Comment by heinthanth** [comment]
Sorry, wrong version number. I changed it now! Thanks for confirming.

**Review by heinthanth — COMMENTED** [review]
Forgive me about wrong version number. It's 11.2.2 ( 20D80 ). Thanks!

**Comment by heinthanth** [comment]
@1alessandro1 @notpeter, I think it can be merged now.

**Comment by ElfSundae** [comment]
Confirmed here.

**Comment by 1alessandro1** [comment]
Merged in https://github.com/notpeter/apple-installer-checksums/commit/daac0bf964e33f3f70b84250e189c92c016c5306

**Comment by markmentovai** [comment]
Verified, sorry for the delay, and thanks to @1alessandro1 for merging.

**Pull request closed without merging**
