### PR TITLE
Add 10.6.3

### PR DESCRIPTION
**Pull request by mrpapersonic**

### CODE REVIEW

**Comment by notpeter** [comment]
Hi! 👋 

Just curious about the 10.6.3 SHA1...since 10.6 was disc only what was the process to create the file corresponding to this hash?

Thanks!

**Comment by mrpapersonic** [comment]
Sorry for not being able to reply... I had a lot to do. The SHA1 calculations were from disk images of the Snow Leopard disc using Disk Utility. I will try to do a SHA256 calculation of it in the future and add it. Thanks!

**Comment by notpeter** [comment]
To confirm, when ripped with disk utility, the files created were of read-only dmg format (not read/write dmg, nor iso).  Just wanted to be consistent because that’s the settings I used for the other CD-based sha checksums here.

Thanks again!

**Comment by mrpapersonic** [comment]
Closing because of new pull request.

**Pull request closed without merging**
