### PR TITLE
Add 11.2.1 (20D75) Big Sur hashes.

### PR DESCRIPTION
**Pull request by urxi**
This is the version that is currently available from the App Store.

### CODE REVIEW

**Comment by 1alessandro1** [comment]
Confirmed here:

image

**Comment by 1alessandro1** [comment]
@markmentovai @notpeter this can be merged I guess

**Comment by ElfSundae** [comment]
Confirmed +1

**Comment by markmentovai** [comment]
Verified, sorry for the delay, and thanks to @1alessandro1 for merging.

**Pull request merged**
