### PR TITLE
Some OS X SHA1 hashes

### PR DESCRIPTION
**Pull request by hirakujira**
This is the one I downloaded from App Store today.

### CODE REVIEW

**Comment by hirakujira** [comment]
I found some legacy OS X Installation disks from Apple's website, which is legit and official.

**Comment by notpeter** [comment]
Hi @hirakujira! Thanks for the contribution.  Any chance you have link for the older releases? Would love to get those merged.

**Comment by hirakujira** [comment]
For 10.4.7 and 10.2, they are in https://developer.apple.com/download/more/ , but you must have a "paid" developer account or they won't show in the list.
For 10.13.6 and 10.7.5, I just downloaded them with `mas` command in a Mac running 10.13

**Comment by matteosecli** [comment]
I can confirm the SHA1 hashes for 17G66.

I've downloaded it from Mojave via App Store, that then uses Software Update to download the full installer. Alternatively, one can use https://github.com/rmc-team/macos-downloader (one can easily check that uses legit Apple links in the Bash script). I've used both methods and run a full diff, the installers are exactly the same.

-----

I also guess the SHA-1 hashes for 14F27, 15G31 and 16G29 refer to the now expired versions. Apple has re-issued resigned installers for those versions, with updated certificates. They are directly downloadable from the following links (Apple's own CDN):

Yosemite: http://updates-http.cdn-apple.com/2019/cert/061-41343-20191023-02465f92-3ab5-4c92-bfe2-b725447a070d/InstallMacOSX.dmg
El Capitan: http://updates-http.cdn-apple.com/2019/cert/061-41424-20191024-218af9ec-cf50-4516-9011-228c78eda3d2/InstallMacOSX.dmg
Sierra: http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg

I get the following SHA-1 hashes:

```console
39c52ff92a4c965b4ca4608a1788732165164abb  ./Install OS X Yosemite.app/Contents/SharedSupport/InstallESD.dmg
27a05174a5cc593d5ff6d61822e9e07ba6aa2288  ./Install OS X El Capitan.app/Contents/SharedSupport/InstallESD.dmg
df682c501d1013435d5c3cb12a26a6fefcbceed0  ./Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg
```

**Pull request closed without merging**
