### PR TITLE
Added macOS Big Sur 11.1 (20C69) SHA-1 and SHA-256

### PR DESCRIPTION
**Pull request by dreamwhite**

### CODE REVIEW

**Comment by 1alessandro1** [comment]
Confirmed here:
SHA-256: 2e2b0e06a4e592b8eca31e6e4eaeccee8442cc166daf36020a4496b838869283 
SHA-1: c21df15ddcc4d392bc82adb813b6b56d0c19b725

image

**Comment by ElfSundae** [comment]
Confirmed +1

**Comment by timoxd7** [comment]
Confirm too

**Comment by 1alessandro1** [comment]
@markmentovai any updates on the authenticity of these hashes?
Can this be merged?

**Comment by notpeter** [comment]
👍  thanks for the contribution @dreamwhite and confirmations @ElfSundae and @timoxd7. Confirmed on my end too.

**Pull request merged**
