### PR TITLE
Add 11.2.3 (20D91) hashes

### PR DESCRIPTION
**Pull request by 1alessandro1**

### CODE REVIEW

**Comment by valar999** [comment]
Confirm `11.2.3` hash.

**Comment by 1alessandro1** [comment]
@notpeter @markmentovai can this be merged?

**Comment by 1alessandro1** [comment]
Done in https://github.com/notpeter/apple-installer-checksums/commit/daac0bf964e33f3f70b84250e189c92c016c5306

**Comment by markmentovai** [comment]
Verified, sorry for the delay, and thanks to @1alessandro1 for merging.

**Pull request closed without merging**
