### PR TITLE
Xcode 11.4 beta, 11.3.x, 11.2.x

### PR DESCRIPTION
**Pull request by sleeve**
Screen Shot 2019-10-11 at 3 18 21 PM

### CODE REVIEW

**Comment by sleeve** [comment]
Screen Shot 2019-11-06 at 9 22 36 AM

**Comment by sleeve** [comment]
Screen Shot 2019-11-13 at 8 50 50 AM
Screen Shot 2019-11-14 at 10 04 38 AM

**Comment by ElfSundae** [comment]
```console
$ shasum ~/Downloads/Xcode_11.3.xip 
7c192e5023cb5d538c601ce301dc69972102d99f  /Users/elfsundae/Downloads/Xcode_11.3.xip
```
image

**Comment by sleeve** [comment]
@ElfSundae Thanks for the info, confirmed! Hopefully we'll get this PR merged someday...

Screen Shot 2019-12-11 at 11 05 00 AM

**Comment by sleeve** [comment]
Screen Shot 2020-02-05 at 10 04 32 AM
Screen Shot 2020-02-05 at 11 32 05 AM

**Comment by sleeve** [comment]
Screen Shot 2020-02-20 at 8 33 37 AM

@markmentovai Still waiting for this to be merged. Feel free to add me as a collaborator if you don't have time to deal with the Xcode releases.

**Comment by notpeter** [comment]
Invite sent.

**Pull request merged**
