### PR TITLE
Add Sierra build

### PR DESCRIPTION
**Pull request by 1alessandro1**
This pull request is correlated to the previous one i made few minutes ago

Obtained from Apple's download link provided in [this page](https://support.apple.com/en-us/HT211683)

http://updates-http.cdn-apple.com/2019/cert/061-39476-20191023-48f365f4-0015-4c41-9f44-39d3d2aca067/InstallOS.dmg

(This hash is from the InstallESD.dmg inside the .pkg)

### CODE REVIEW

**Comment by markmentovai** [comment]
> (This hash is from the InstallESD.dmg inside the .pkg)

I found that not to be the case. The hash is from InstallOS.pkg inside the .dmg. There’s an InstallESD.dmg in that .pkg, which is what we’d normally be after, but that’s not what you hashed here.

I don’t believe that 16G27 is correct. The BaseSystem.dmg in this one reports 16G29.

Can you share more about where you got this link, hash, and build ID?

#103 too.

**Comment by 1alessandro1** [comment]
The 16G27 can be found inside the Info.plist once you install the .pkg, same thing applies for the other PR.
 

> Can you share more about where you got this link, hash, and build ID?

I found it here: https://support.apple.com/en-us/HT211683

And the same SHA1SUMS are present in another PR:

https://github.com/notpeter/apple-installer-checksums/pull/71#issuecomment-691672417

image

**Comment by 1alessandro1** [comment]
Any updates?

**Comment by markmentovai** [comment]
As in https://github.com/notpeter/apple-installer-checksums/pull/103#issuecomment-735045372.

**Comment by 1alessandro1** [comment]
Closing.

This file can be downloaded directly from apple servers if anybody is willing to check the build number and the hashes, links are above.

**Pull request closed without merging**
