### PR TITLE
Added macOS Monterey 12.0db7 hashes

### PR DESCRIPTION
**Pull request by dreamwhite**
Users are encouraged to confirm their own

### CODE REVIEW

**Comment by dreamwhite** [comment]
Please note that 12.0db7 installer is broken and will probably be re-uploaded on Apple servers

**Comment by markmentovai** [comment]
Hi! I see new hashes now, do you want to check and update?

(I see SHA-256 371f2afd…0589705d)

I can also update myself if you’re unable.

**Comment by dreamwhite** [comment]
> Hi! I see new hashes now, do you want to check and update?

Sure, I voluntarily waited some days hoping that the installer is fixed (by broken installer I mean that the Install-macOS.dmg size is like 32MB).
I'm actually downloading macOS 12.0db7 again from Apple DeveloperSeed catalog - using [munki macadmin-scripts](https://github.com/munki/macadmin-scripts/blob/main/installinstallmacos.py) with `-seedprogram DeveloperSeed` args - and in 45 minutes or less I'll get the fully built installer and will update the hashes consequently.

I hope it's not a problem 😅

**Comment by dreamwhite** [comment]
image

I'm sorry but the installer itself can't be created onto a DMG file😅.
In any case I can get the InstallAssistant.pkg and extract the SharedSupport.dmg out of it using `pkgutil --expand InstallAssistant.pkg FANCY_DIRECTORY_NAME`.

The hashes are:

- SHA256: `5f667142dd2bad50ae2f6914ed4ce5b35010a6905ce9efc39f4231bfd079b5d9`
- SHA1: `1c93f34badb10fb13340f927b29a55d794812a25`

I don't think your hashes are the same, hence I suggest waiting another confirmation from users who managed to get the not borked installer.

From what I'm reading on InsanelyMac forum, the install script (the one that is responsible of copying stuff onto the USB volume) is broken and thus needs to be fixed by manually extracting `SharedSupport.dmg` content onto SharedSupport directory of the installer .app itself.

For more infos check [here](https://www.insanelymac.com/forum/topic/348725-pre-release-macos-monterey/page/62/?tab=comments#comment-2767386)

**Comment by markmentovai** [comment]
Freaky. I have my own tooling to download these from Apple, and to turn them into installer .apps, and was able to make a working 12.0db7 21A5522h, use its `createinstallmedia`, and install a fresh OS, without ever experiencing the problem. Now that you mention it, I looked and found the bug Apple accidentally introduced in the `postinstall` phase.

Tip: don’t extract `SharedSupport.dmg` from `InstallAssistant.pkg`. Instead, use `InstallAssistant.pkg` as `SharedSupport.dmg`. It’s tricky like that. You can learn more from `postinstall_actions/link_shared_support.*`. That explains our different hashes.

**Comment by dreamwhite** [comment]
Oh okay, so basically I should get the SHA of InstallAssistant.pkg?
Eventually can you link your tooling to download from Apple?

**Comment by markmentovai** [comment]
> Oh okay, so basically I should get the SHA of InstallAssistant.pkg?

Yes, `InstallAssistant.pkg` is what actually becomes `SharedSupport.dmg`. This is confusing, because it’s _both_ a `.pkg` and a `.dmg` simultaneously. It’s even more confusing because the `.pkg` also expands to a nearly-identical `SharedSupport.dmg` that’s _not_ also a `.pkg`. The “outer” polyglot `.pkg`/`.dmg` is the one that winds up inside the `.app` and it’s the one whose hash we want.

> Eventually can you link your tooling to download from Apple?

Eventually, yes.

What I can tell you for now is: [InstallAssistant.pkg](https://swcdn.apple.com/content/downloads/06/05/002-02555-A_W1UDYXDDUZ/aorhr3psk29e00zwe7r41ur3humfp9cf80/InstallAssistant.pkg). This is the same as the link that [Mr. Macintosh gives on its page](https://mrmacintosh.com/macos-12-monterey-full-installer-database-download-directly-from-apple/), and it ought to be the same as what [macadmin-scripts/installinstallmacos.py](https://github.com/munki/macadmin-scripts/blob/03ef2ba0fed4a6e99de0a0acf7ea9e3949a47287/installinstallmacos.py) downloads, as its catalog/download logic is very similar to mine.

**Comment by dreamwhite** [comment]
@markmentovai here I am with the hashes:

- **SHA-256**: `371f2afda435b03e945cc91fc0fb48a330a32045ed9bd267bf8d49660589705d`
- **SHA-1**: `273401148318acadb95349f9caf6b5ef619c3579`


> (I see SHA-256 371f2afd…0589705d)

I think at this point that the hashes are the same, so I can commit them and convert this PR from draft to Ready to review. Do you agree?

**Comment by markmentovai** [comment]
Those hashes match. Thanks!

I think we should continue calling it `SharedSupport.dmg` because that’s what it’s named when it’s in the user’s hands, in the `.app`. (And in this case, it would be, but for Apple’s bug.)

**Comment by dreamwhite** [comment]
Okay perfect. Then I'm commiting right now the new hashes so you'll be able to merge the PR.
Again many thanks

**Pull request merged**
