### PR TITLE
Checksums for macOS 10.15.3 (19D2064) and macOS 10.15.4 (19E266)

### LINKED ISSUE #74: Add checksums for macOS 10.15.3 (19D2064) and macOS 10.15.4 (19E266)
There are new builds

### PR DESCRIPTION
**Pull request by vitalys**
Fixes #74

### CODE REVIEW

**Comment by markmentovai** [comment]
Do you have the SHA-256 checksums too? We include those in the .

**Comment by vitaliy-solarwinds** [comment]
@markmentovai yep, let me add them for 10.15.3/10.15.4/10.15.2/10.15.0 in few hours

**Comment by vitalys** [comment]
@markmentovai yep, let me add them for 10.15.3/10.15.4/10.15.2/10.15.0 in few hours

**Comment by markmentovai** [comment]
Thanks. I just added 10.15.4, but you can do it for the others.

**Comment by vitalys** [comment]
I'll update my branch and reopen PR after this

**Pull request closed without merging**
